# Generated by Django 4.2.5 on 2023-09-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewed_by_student',
        ),
        migrations.RemoveField(
            model_name='product',
            name='students',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
